version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/docker-node-mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '6000:27017'
